### PR TITLE
Announcement bar no longer blocks server status

### LINKED ISSUE #154: Announcement bar blocks server status badge in fullscreen
As the title says, in fullscreen you can't see the server status when there are announcements
image

### PR DESCRIPTION
**Pull request by michaelni678**
Closes #154

Announcement bar now goes to the bottom of screen when fullscreened.

https://user-images.githubusercontent.com/82001942/161842911-18e4b429-b45b-458b-9da9-4c94e5b39a7d.mp4

### CODE REVIEW

**Comment by Gerzer** [comment]
Is there any way to keep the Announcements ticker at the top of the screen in full-screen mode? @Isaac-the-Man, what do you think?

**Comment by Isaac-the-Man** [comment]
At the moment it'll block some other information on the the top. But it's definitely possible to squeeze out a space on the top for it.

**Review by Isaac-the-Man — CHANGES_REQUESTED** [review]
Use mixins to replace computed `isFsMode()`.

**Comment by michaelni678** [comment]
now uses mixins

**Review by Isaac-the-Man — APPROVED** [review]

**Pull request merged**
